"""initial migration

Revision ID: e9f3f88485ab
Revises: 
Create Date: 2026-03-30 20:54:27.050360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f3f88485ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('locations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('idx_sale_batches_date', table_name='sale_batches')
    op.drop_index('idx_sale_batches_invoice', table_name='sale_batches')
    op.alter_column('sales', 'shoe_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales', 'size_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_index('idx_sales_batch', table_name='sales')
    op.drop_index('idx_sales_date', table_name='sales')
    op.drop_index('idx_sales_shoe', table_name='sales')
    op.drop_constraint('sales_shoe_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'shoes', ['shoe_id'], ['id'])
    op.drop_constraint('shoe_colors_shoe_id_fkey', 'shoe_colors', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_colors', 'shoes', ['shoe_id'], ['id'])
    op.drop_constraint('shoe_materials_shoe_id_fkey', 'shoe_materials', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_materials', 'shoes', ['shoe_id'], ['id'])
    op.drop_index('idx_shoe_sizes_shoe', table_name='shoe_sizes')
    op.drop_index('idx_shoe_sizes_size', table_name='shoe_sizes')
    op.drop_index('idx_shoe_sizes_stock', table_name='shoe_sizes')
    op.drop_constraint('shoe_sizes_shoe_id_fkey', 'shoe_sizes', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_sizes', 'shoes', ['shoe_id'], ['id'])
    op.alter_column('shoes', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('shoes', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('idx_shoes_active', table_name='shoes')
    op.drop_index('idx_shoes_brand', table_name='shoes')
    op.drop_index('idx_shoes_category', table_name='shoes')
    op.drop_index('idx_shoes_gender', table_name='shoes')
    op.drop_index('idx_shoes_location', table_name='shoes')
    op.drop_index('idx_shoes_sku', table_name='shoes')
    op.drop_index('idx_shoes_supplier', table_name='shoes')
    op.drop_constraint('shoes_sku_key', 'shoes', type_='unique')
    op.create_index(op.f('ix_shoes_sku'), 'shoes', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoes_sku'), table_name='shoes')
    op.create_unique_constraint('shoes_sku_key', 'shoes', ['sku'])
    op.create_index('idx_shoes_supplier', 'shoes', ['supplier_id'], unique=False)
    op.create_index('idx_shoes_sku', 'shoes', ['sku'], unique=False)
    op.create_index('idx_shoes_location', 'shoes', ['location_id'], unique=False)
    op.create_index('idx_shoes_gender', 'shoes', ['gender_id'], unique=False)
    op.create_index('idx_shoes_category', 'shoes', ['category_id'], unique=False)
    op.create_index('idx_shoes_brand', 'shoes', ['brand_id'], unique=False)
    op.create_index('idx_shoes_active', 'shoes', ['is_active'], unique=False)
    op.alter_column('shoes', 'image_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shoes', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'shoe_sizes', type_='foreignkey')
    op.create_foreign_key('shoe_sizes_shoe_id_fkey', 'shoe_sizes', 'shoes', ['shoe_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_shoe_sizes_stock', 'shoe_sizes', ['stock_quantity'], unique=False)
    op.create_index('idx_shoe_sizes_size', 'shoe_sizes', ['size_id'], unique=False)
    op.create_index('idx_shoe_sizes_shoe', 'shoe_sizes', ['shoe_id'], unique=False)
    op.drop_constraint(None, 'shoe_materials', type_='foreignkey')
    op.create_foreign_key('shoe_materials_shoe_id_fkey', 'shoe_materials', 'shoes', ['shoe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shoe_colors', type_='foreignkey')
    op.create_foreign_key('shoe_colors_shoe_id_fkey', 'shoe_colors', 'shoes', ['shoe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_shoe_id_fkey', 'sales', 'shoes', ['shoe_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_sales_shoe', 'sales', ['shoe_id'], unique=False)
    op.create_index('idx_sales_date', 'sales', ['sale_date'], unique=False)
    op.create_index('idx_sales_batch', 'sales', ['batch_id'], unique=False)
    op.alter_column('sales', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('sales', 'size_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sales', 'shoe_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_sale_batches_invoice', 'sale_batches', ['invoice_number'], unique=False)
    op.create_index('idx_sale_batches_date', 'sale_batches', ['sale_date'], unique=False)
    op.alter_column('locations', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('brands', 'logo_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
